#!/usr/bin/env bash

set -eo pipefail

export NODE_OPTIONS="${NODE_OPTIONS:---max-old-space-size=4096}"

# Exclude tests that require old (non-VM) SCI namespaces or crash on missing CLJS interop
EXCLUDE_RE='(?!sci\.(async|js-libs|js|interop|io)).*-test$'

echo 'Running CLJS test in Node with optimizations :none'
echo '{:optimizations :none}' > cljs-opts.edn
clojure -M:test:cljs-test-runner -c cljs-opts.edn -r "$EXCLUDE_RE" $@

echo 'Running CLJS test in Node with optimizations :advanced'
echo '{:optimizations :advanced}' > cljs-opts.edn
clojure -M:test:cljs-test-runner -c cljs-opts.edn -r "$EXCLUDE_RE" $@
